### PR TITLE
Typescript on Core Bot Files

### PR DESCRIPTION
**Pull request by shadowtime2000**
Resolves #63.

### CODE REVIEW

**Comment by shadowtime2000** [comment]
Hmm, I don't understand why those checks don't pass.

**Comment by peterthehan** [comment]
Hmm previous commits seem to have passed checks, maybe something was introduced between either commits
5849cb7 or 2da4c29 that broke something?

**Comment by shadowtime2000** [comment]
All I did was `git checkout -b typescript` and then in the `master` branch I rebased it. I think it may be a glitch with the Github actions, because it says 6 checks happened, 3 passing, 3 failing, basically just a duplicate of the same check on the same commit. That seems strange.

**Comment by peterthehan** [comment]
if i'm reading the logs right, it seems like it's trying to checkout a `typescript` branch from _this_ repository, not your forked repository... 🤔

**Comment by peterthehan** [comment]
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ seems to be a recent update that's relevant here 👀

**Comment by shadowtime2000** [comment]
#69 I will send a PR with these changes to the template repo.

**Pull request closed without merging**
