### PR TITLE
create-discord-bot v2

### PR DESCRIPTION
**Pull request by Bytooo**
- default language is now TypeScript for the main script
- uses a more Object Oriented approach
- adds script statuses
- separates build and update process
- adds a verification function for the app

### CODE REVIEW

**Comment by shadowtime2000** [comment]
So we are going to be committing compiled JS files?

**Comment by peterthehan** [comment]
I think so, I tried a bunch of different stuff (and I'm sure you have as well) it's the _least_ hacky solution afaict.

**Comment by shadowtime2000** [comment]
I am a little confused though. Are we going to merge #47 or this?

**Comment by peterthehan** [comment]
So @Bytooo was originally working on #22 and the original workflow didn't facilitate e2e testing well. I think this PR is to enable that. And I realize this sort of change kinda flips everything on its head but I think it's worth it if we can get testing in.

On that note, @Bytooo, I would prefer tests done in this PR before actually merging since otherwise this is just a refactor.

**Comment by Bytooo** [comment]
Aight

**Comment by peterthehan** [comment]
Going to close this since it's stale.

**Pull request closed without merging**
