### PR TITLE
Added Nodemon

### PR DESCRIPTION
**Pull request by shadowtime2000**
Added `nodemon` to the project dependencies and changed the `start` script to run `nodemon ./src/index.js` instead of `node ./src/index.js`.

### CODE REVIEW

**Comment by peterthehan** [comment]
Hey @shadowtime2000 thanks for the PR, However, I'd prefer to keep the bot template rather "dumb" and leave it up for the user to customize. Basically, I would prefer to not add another dependency if I could avoid it. Lmk your thoughts on this.

**Comment by shadowtime2000** [comment]
What if we add it as a setup question when they run `npx peterthehan/create-discord-bot`.

**Comment by peterthehan** [comment]
Hmm, that seems reasonable enough. Before I commit to it, let me do some research into nodemon (I'm not familiar with this package).

**Comment by Bytooo** [comment]
Nodemon is usually used as a development dependency so suggest it being installed as a dev dependency with `npm install -D nodemon` instead of it being installed as a dependency since nodemon is not required for the bot to run.

With this change you could use nodemon if you install the dependencies with `npm install` but if you don't want to use it you could do `npm install --only=production` or `npm ci --only=production` preventing nodemon from being installed.

As for the npm script you could add a "nodemon" script instead of replacing the default start script with nodemon.

**Comment by shadowtime2000** [comment]
So we could add `nodemon` as a dev dependency and have it run in a script like `dev`.

**Comment by peterthehan** [comment]
I think there are some solid ideas here. To do this justice, I'm going to close this PR and flush out a more comprehensive plan for allowing for some QOL dev dependencies to be selected in the installation process.

Off the top of my head, nodemon and prettier are nice candidates. I'll open up an issue for this and tackle this sometime tomorrow.

**Pull request closed without merging**
