### PR TITLE
On The Fly Typescript Compilation

### PR DESCRIPTION
**Pull request by shadowtime2000**
Implemented usage of the Typescript Compiler API to compile typescript on the fly.

### CODE REVIEW

**Comment by peterthehan** [comment]
Found an arguably more native solution over in `test_ts_npx`. You can test via `npx peterthehan/create-discord-bot#test_ts_npx`.

**Comment by shadowtime2000** [comment]
> Found a more native solution over in `test_ts_npx`. You can test via `npx peterthehan/create-discord-bot#test_ts_npx`. PR at #62.

Your solution seems to be what we tried before, requiring users to have `ts-node` installed globally. I ran `npm uninstall ts-node -g` and then I ran `npx peterthehan/create-discord-bot#test_ts_npx` and it gave me the error `'"ts-node-script"' is not recognized as an internal or external command, operable program or batch file.`

**Comment by peterthehan** [comment]
Oh shoot you're right. I should have tested elsewhere, jumped the gun there.

**Comment by shadowtime2000** [comment]
I think I messed something up with the relative paths. We could also use `process` to force the global install of `ts-node` and `typescript`.

**Comment by shadowtime2000** [comment]
Looking into it this seems to be a lot more complex than it should be so I will be closing this. Later, though, I will open another pull request with a more easy to understand and change solution.

**Pull request closed without merging**
